const adminTableFields = [
  {
    name: 'name',
    label: 'Назва',
    type: 'text',
    maxLength: 50,
    as: 'input',
    required: true,
  },
  {
    name: 'date',
    label: 'Дата',
    type: 'date',
    as: 'input',
    required: true,
  },
  {
    name: 'short_description',
    label: 'Короткий опис',
    type: 'textarea',
    rows: 3,
    maxLength: 150,
    as: 'textarea',
    resize: 'none',
    required: true,
  },
  {
    name: 'long_description',
    label: 'Довгий опис',
    type: 'textarea',
    rows: 5,
    maxLength: 10000,
    as: 'textarea',
    required: true,
  },
  {
    name: 'social_networks.instagram',
    label: 'Посилання на інстаграм пост',
    placeholder: 'https://instagram.com/archangelsofkyiv',
    as: 'input',
    type: 'text',
    required: true,
  },
  {
    name: 'social_networks.facebook',
    label: 'Посилання на facebook пост',
    placeholder: 'https://www.facebook.com/archangelsofkyiv',
    as: 'input',
    type: 'text',
  },
  {
    name: 'photo',
    label: 'Фото (jpg, png, jpeg)',
    type: 'file',
    as: 'input',
  },
];

const adminPartnersFields = [
  {
    name: 'name',
    label: 'Назва організації',
    type: 'text',
    maxLength: 50,
    as: 'input',
    required: true,
  },
  {
    name: 'short_description',
    label: 'Короткий опис (діяльності)',
    type: 'textarea',
    rows: 3,
    maxLength: 150,
    as: 'textarea',
    resize: 'none',
    required: true,
  },
  {
    name: 'full_description',
    label: 'Довгий опис',
    type: 'textarea',
    rows: 5,
    maxLength: 10000,
    as: 'textarea',
  },
  {
    name: 'social_networks.instagram',
    label: 'Посилання на інстаграм',
    placeholder: 'https://instagram.com/archangelsofkyiv',
    as: 'input',
    type: 'text',
    required: true,
  },
  {
    name: 'social_networks.facebook',
    label: 'Посилання на facebook',
    placeholder: 'https://www.facebook.com/archangelsofkyiv',
    as: 'input',
    type: 'text',
  },
  {
    name: 'photo',
    label: 'Фото (jpg, png, jpeg)',
    type: 'file',
    as: 'input',
  },
];

const adminProjectsFields = [
  {
    name: 'name',
    label: 'Назва',
    type: 'text',
    maxLength: 50,
    as: 'input',
    required: true,
  },
  {
    name: 'date',
    label: 'Дата',
    type: 'date',
    as: 'input',
    required: true,
  },
  {
    name: 'short_description',
    label: 'Короткий опис',
    type: 'textarea',
    rows: 3,
    maxLength: 150,
    as: 'textarea',
    resize: 'none',
    required: true,
  },
  {
    name: 'long_description',
    label: 'Довгий опис',
    type: 'textarea',
    rows: 5,
    maxLength: 10000,
    as: 'textarea',
    required: true,
  },
  {
    name: 'social_networks.instagram',
    label: 'Посилання на інстаграм пост',
    placeholder: 'https://instagram.com/archangelsofkyiv',
    as: 'input',
    type: 'text',
    required: true,
  },
  {
    name: 'social_networks.facebook',
    label: 'Посилання на facebook пост',
    placeholder: 'https://www.facebook.com/archangelsofkyiv',
    as: 'input',
    type: 'text',
  },
  {
    name: 'photo',
    label: 'Фото (jpg, png, jpeg)',
    type: 'file',
    as: 'input',
  },
]

export { 
  adminTableFields,
  adminPartnersFields,
  adminProjectsFields,
};
